# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protocol-level-tokens.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
    Optional,
)

import betterproto

from ... import v2 as __v2__


@dataclass(eq=False, repr=False)
class Cbor(betterproto.Message):
    """A CBOR encoded bytestring"""

    value: bytes = betterproto.bytes_field(1)
    """A CBOR encoded byte string."""


@dataclass(eq=False, repr=False)
class TokenId(betterproto.Message):
    """Token ID: a unique symbol and identifier of a protocol level token."""

    value: str = betterproto.string_field(1)
    """
    Unique identifier for the token, guaranteed to be distinct across the
    entire concordium blockchain. The token id must be between 1 and 128 bytes
    long and consist of only a-z, A-Z, 0-9, `.`, `%` and `-`.
    """


@dataclass(eq=False, repr=False)
class LockId(betterproto.Message):
    """Lock ID: a trio of numbers that together uniquely identify a lock."""

    account_index: int = betterproto.uint64_field(1)
    """The account index of the account that created the lock."""

    sequence_number: int = betterproto.uint64_field(2)
    """The sequence number of the transaction that created the lock."""

    creation_order: int = betterproto.uint64_field(3)
    """
    The 0-based creation order of the lock within the transaction that created
    it.
    """


@dataclass(eq=False, repr=False)
class TokenModuleRef(betterproto.Message):
    """A token module reference. This is always 32 bytes long."""

    value: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class TokenAmount(betterproto.Message):
    """
    PLT amount representation. The actual amount is computed as `value *
    10^(-decimals)`.
    """

    value: int = betterproto.uint64_field(1)
    """The digits of the amount."""

    decimals: int = betterproto.uint32_field(2)
    """Number of decimals in the representation"""


@dataclass(eq=False, repr=False)
class TokenState(betterproto.Message):
    """Token state at the block level"""

    token_module_ref: "TokenModuleRef" = betterproto.message_field(1)
    """The reference of the module implementing this token."""

    decimals: int = betterproto.uint32_field(3)
    """Number of decimals in the decimal number representation of amounts."""

    total_supply: "TokenAmount" = betterproto.message_field(4)
    """The total available token supply."""

    module_state: "Cbor" = betterproto.message_field(5)
    """
    Token module specific state, such as token name, feature flags, meta data.
    """


@dataclass(eq=False, repr=False)
class TokenAccountState(betterproto.Message):
    """Token state at the account level"""

    balance: "TokenAmount" = betterproto.message_field(1)
    """The available balance."""

    module_state: Optional["Cbor"] = betterproto.message_field(
        4, optional=True, group="_module_state"
    )
    """
    Token module specific account state, such as whether the account is on the
    allow or deny list.
    """


@dataclass(eq=False, repr=False)
class TokenModuleEvent(betterproto.Message):
    """
    Single token event originating from a token module as part of a token
    transaction.
    """

    type: str = betterproto.string_field(1)
    """The type of the event."""

    details: "Cbor" = betterproto.message_field(2)
    """The CBOR encoded event details."""

    token_id: Optional["TokenId"] = betterproto.message_field(
        3, optional=True, group="_token_id"
    )
    """
    The Token ID of the token generating the event. In the context of a
    `TokenEvent`, this should be absent (as it is already specified). In the
    context of a `MetaEvent`, this must be present.
    """


@dataclass(eq=False, repr=False)
class TokenHolder(betterproto.Message):
    """
    A token holder is an entity that can hold tokens. Currently, this is
    limited to accounts, but in the future it may be extended to other
    entities.
    """

    account: "__v2__.AccountAddress" = betterproto.message_field(1, group="address")
    """The account address of the holder."""


@dataclass(eq=False, repr=False)
class TokenTransferEvent(betterproto.Message):
    """
    An event emitted when a transfer of tokens from `from` to `to` is
    performed.
    """

    from_: "TokenHolder" = betterproto.message_field(1)
    """The token holder from which the tokens are transferred."""

    to: "TokenHolder" = betterproto.message_field(2)
    """The token holder to which the tokens are transferred."""

    amount: "TokenAmount" = betterproto.message_field(3)
    """The amount of tokens transferred."""

    memo: Optional["__v2__.Memo"] = betterproto.message_field(
        4, optional=True, group="_memo"
    )
    """
    An optional memo field that can be used to attach a message to the token
    transfer.
    """

    from_lock: Optional["LockId"] = betterproto.message_field(
        5, optional=True, group="_from_lock"
    )
    """
    When the funds originate on the locked balance of an account, the  identity
    of the lock controlling the funds. Absent when the funds are not on the
    locked balance of the originating account.
    """

    to_lock: Optional["LockId"] = betterproto.message_field(
        6, optional=True, group="_to_lock"
    )
    """
    When the funds are transferred into the control of a lock, the identity of
    the lock assuming control of the funds. Absent when the funds are sent to
    the available balance of the receiving account.
    """

    token_id: Optional["TokenId"] = betterproto.message_field(
        7, optional=True, group="_token_id"
    )
    """
    The token being transferred. In the context of a `TokenEvent`, which
    already specifies the token, this is absent. In the context of a
    `MetaEvent`, it must be present.
    """


@dataclass(eq=False, repr=False)
class TokenSupplyUpdateEvent(betterproto.Message):
    """
    An event emitted when the token supply is updated, i.e. by minting/burning
    tokens to/from the balance of the `target`.
    """

    target: "TokenHolder" = betterproto.message_field(1)
    """The token holder the balance update is performed on."""

    amount: "TokenAmount" = betterproto.message_field(2)
    """The balance difference to be applied to the target."""

    token_id: Optional["TokenId"] = betterproto.message_field(
        3, optional=True, group="_token_id"
    )
    """
    The Token ID of the token generating the event. In the context of a
    `TokenEvent`, this should be absent (as it is already specified). In the
    context of a `MetaEvent`, this must be present.
    """


@dataclass(eq=False, repr=False)
class TokenEvent(betterproto.Message):
    """Token event originating from token transactions."""

    token_id: "TokenId" = betterproto.message_field(1)
    """The Token ID."""

    module_event: "TokenModuleEvent" = betterproto.message_field(2, group="event")
    """An event emitted by the token module."""

    transfer_event: "TokenTransferEvent" = betterproto.message_field(3, group="event")
    """An event emitted when a transfer of tokens is performed."""

    mint_event: "TokenSupplyUpdateEvent" = betterproto.message_field(4, group="event")
    """
    An event emitted when the token supply is updated by minting tokens to a
    token holder.
    """

    burn_event: "TokenSupplyUpdateEvent" = betterproto.message_field(5, group="event")
    """
    An event emitted when the token supply is updated by burning tokens from
    the balance of a token holder.
    """


@dataclass(eq=False, repr=False)
class TokenEffect(betterproto.Message):
    """Token events originating from token transactions."""

    events: List["TokenEvent"] = betterproto.message_field(1)
    """Events emitted by the token."""


@dataclass(eq=False, repr=False)
class LockCreateEvent(betterproto.Message):
    """A new lock was created."""

    lock_id: "LockId" = betterproto.message_field(1)
    """The Lock ID of the newly-created lock."""

    lock_config: "Cbor" = betterproto.message_field(2)
    """The CBOR-encoded configuration of the lock."""


@dataclass(eq=False, repr=False)
class LockDestroyEvent(betterproto.Message):
    """
    A lock was destroyed. Before this event can occur, the balance controlled
    by the lock must be zero.
    """

    lock_id: "LockId" = betterproto.message_field(1)
    """The Lock ID of the destroyed lock."""


@dataclass(eq=False, repr=False)
class MetaEvent(betterproto.Message):
    """
    An event that can occur during execution of a meta-update transaction.
    """

    module_event: "TokenModuleEvent" = betterproto.message_field(2, group="event")
    """An event emitted by the token module."""

    transfer_event: "TokenTransferEvent" = betterproto.message_field(3, group="event")
    """An event emitted when a transfer of tokens is performed."""

    mint_event: "TokenSupplyUpdateEvent" = betterproto.message_field(4, group="event")
    """
    An event emitted when the token supply is updated by minting tokens to a
    token holder.
    """

    burn_event: "TokenSupplyUpdateEvent" = betterproto.message_field(5, group="event")
    """
    An event emitted when the token supply is updated by burning tokens from
    the balance of a token holder.
    """

    lock_create_event: "LockCreateEvent" = betterproto.message_field(6, group="event")
    """A lock creation event."""

    lock_destroy_event: "LockDestroyEvent" = betterproto.message_field(7, group="event")
    """A lock destruction event."""


@dataclass(eq=False, repr=False)
class MetaEffect(betterproto.Message):
    """Events originating from a meta-update transaction."""

    events: List["MetaEvent"] = betterproto.message_field(1)
    """The events."""


@dataclass(eq=False, repr=False)
class TokenModuleRejectReason(betterproto.Message):
    """
    Details provided by the token module in the event of rejecting a
    transaction.
    """

    token_id: "TokenId" = betterproto.message_field(1)
    """The Token ID of the protocol-level token."""

    type: str = betterproto.string_field(2)
    """The type of the reject reason."""

    details: Optional["Cbor"] = betterproto.message_field(
        3, optional=True, group="_details"
    )
    """(Optional) CBOR-encoded details."""


@dataclass(eq=False, repr=False)
class CreatePlt(betterproto.Message):
    """Update payload for creating a new protocol-level token"""

    token_id: "TokenId" = betterproto.message_field(1)
    """The Token ID of the protocol-level token."""

    token_module: "TokenModuleRef" = betterproto.message_field(2)
    """The hash that identifies the token module implementation."""

    decimals: int = betterproto.uint32_field(4)
    """
    The number of decimal places used in the representation of amounts of this
    token. This determines the smallest representable fraction of the token.
    This can be at most 255.
    """

    initialization_parameters: "Cbor" = betterproto.message_field(5)
    """The initialization parameters of the token, encoded in CBOR."""


@dataclass(eq=False, repr=False)
class TokenCreationDetails(betterproto.Message):
    """Details about the creation of a protocol-level token."""

    create_plt: "CreatePlt" = betterproto.message_field(1)
    """The update payload used to create the token."""

    events: List["TokenEvent"] = betterproto.message_field(2)
    """
    The events generated by the token module during the creation of the token.
    """


@dataclass(eq=False, repr=False)
class TokenAuthorizations(betterproto.Message):
    """
    The authorizations for a token. The actual authorizations are found in the
    CBOR encoded `details`.
    """

    token_id: "TokenId" = betterproto.message_field(1)
    """The canonical token identifier."""

    details: "Cbor" = betterproto.message_field(2)
    """
    The CBOR encoded authorizations for the token represented by the
    `token_id`.
    """
