import httpx2 as httpx
from ccdexplorer.site_user import SiteUser
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from ccdexplorer.charts.registry import ALL_SPECS
from ccdexplorer.env import environment

from ccdexplorer.ccdexplorer_site.app.state import (
    get_httpx_client,
    get_labeled_accounts,
    get_user_detailsv2,
)
from ccdexplorer.ccdexplorer_site.app.utils import page_theme
from ccdexplorer.charts import chart_path

router = APIRouter()


def has_image(spec) -> bool:
    """Whether the gallery can show a thumbnail for this chart.

    Read off the spec rather than a list here, so a chart that gains an image
    route says so in one place.
    """
    return spec.has_image


#: The order the gallery reads in, matching the bot's category menu.
CATEGORY_ORDER = ("chain", "accounts", "staking", "exchanges", "plt", "agents")


def categories_with_counts() -> list[tuple[str, int]]:
    """The categories that have charts, in reading order, with how many.

    A category with nothing in it is not listed: an empty tile is a promise
    of nothing.
    """
    counts: dict[str, int] = {}
    for spec in ALL_SPECS:
        if spec.listed:
            counts[spec.category] = counts.get(spec.category, 0) + 1
    return [(c, counts[c]) for c in CATEGORY_ORDER if c in counts]


def specs_in(category: str) -> list:
    return [s for s in ALL_SPECS if s.category == category]


def listed_specs(category: str) -> list:
    """What the gallery shows for a category.

    Not every registered chart: the Kraken candles are one chart at seven
    intervals, and the price charts plot the same price from the chain's own
    rate. Listing all of them filled the category with the same picture.
    """
    return [s for s in specs_in(category) if s.listed]


#: Where the generated covers are served from. Files rather than renders:
#: six full-size figures through kaleido was the reason the index was slow.
COVER_DIR = "/static/charts"

#: Categories whose name is not simply capitalised. PLT is an initialism and
#: capitalize() renders it "Plt".
_CATEGORY_LABELS = {"plt": "PLT"}


def category_label(category: str) -> str:
    return _CATEGORY_LABELS.get(category, category.capitalize())


#: Which chart stands for each category on the index.
#:
#: Chosen rather than taken in registry order. That order gave chain and
#: accounts two bar charts of near-identical shape, picked a line for
#: staking that said little at thumbnail size, and left PLT with nothing at
#: all because its chart is refused by the generic pipeline -- which was
#: only ever a limitation of how the covers were generated, not a reason for
#: the index to have a hole in it.
COVER_CHART = {
    "chain": "transactions_count",
    "accounts": "accounts_growth",
    "staking": "staking_avg_delegator_stake",
    "exchanges": "ccd_kraken_4h",
    "plt": "plt_tvl",
    "agents": "agent_registries",
}


def cover_image(category: str, theme: str = "light") -> str:
    """The stored cover for a category in one theme, or "" where there is none.

    One file per theme. A stored image cannot follow the theme toggle the way
    an htmx-driven plot can, so both are generated and the switcher picks --
    otherwise a reader who asked for light went on looking at dark tiles.

    Regenerated by `just chart-covers`.
    """
    if cover_chart(category) is None:
        return ""
    return f"{COVER_DIR}/{category}-{theme}.png"


def tile_href(spec, net: str) -> str:
    """Where a tile leads.

    A configurable page where there is one; otherwise the chart's own page,
    because a tile that leads nowhere is worse than no tile.

    Asked of chart_path rather than built here, because a chart's page is not
    always at its own slug: the seven Kraken intervals share one.
    """
    if spec.has_page:
        return chart_path(spec, None, net)
    if spec.has_image:
        return f"/plots/{net}/{spec.name}"
    return ""


def cover_chart(category: str):
    """The chart a category's cover is drawn from, or None for no such category.

    One image per category rather than one per chart: twenty thumbnails on
    the index meant twenty kaleido renders on a cold cache, which was the
    first thing anyone said about the page.

    Named in COVER_CHART rather than inferred. It used to be the first chart
    the generic builder could draw, which is a property of the generator
    rather than of what the picture should be.
    """
    from ccdexplorer.charts.registry import BY_NAME

    return BY_NAME.get(COVER_CHART.get(category, ""))


@router.get("/{net}/charts", response_class=HTMLResponse)
async def get_charts_home(
    request: Request,
    net: str,
    tags: dict = Depends(get_labeled_accounts),
    httpx_client: httpx.AsyncClient = Depends(get_httpx_client),
):
    request.state.api_calls = {}

    user: SiteUser | None = await get_user_detailsv2(request)

    return request.app.templates.TemplateResponse(
        request,
        "charts/charts_home.html",
        {
            "request": request,
            "net": net,
            "tags": tags,
            "user": user,
            "env": environment,
            "categories": categories_with_counts(),
            "cover_image": cover_image,
            "category_label": category_label,
            # Which cover to serve on the first paint. page_theme, not the
            # plot resolver: a visitor with no cookie is looking at a dark
            # page, because that is what base.html's head script assumes,
            # and light tiles on it correct themselves only when toggled.
            "theme": page_theme(request),
        },
    )


@router.get("/{net}/charts/category/{category}", response_class=HTMLResponse)
async def get_charts_category(
    request: Request,
    net: str,
    category: str,
    tags: dict = Depends(get_labeled_accounts),
    httpx_client: httpx.AsyncClient = Depends(get_httpx_client),
):
    """One category's charts, which is where the thumbnails live now."""
    members = listed_specs(category)
    if not members:
        raise HTTPException(status_code=404, detail=f"No such chart category: {category}")

    request.state.api_calls = {}
    user: SiteUser | None = await get_user_detailsv2(request)
    return request.app.templates.TemplateResponse(
        request,
        "charts/charts_category.html",
        {
            "request": request,
            "net": net,
            # Named in the url the tile asks for, not left to the cookie.
            # The response varies by theme but the url did not, so the
            # browser served whichever it had cached first -- dark tiles on
            # a page that had just been switched to light.
            "theme": page_theme(request),
            "tags": tags,
            "user": user,
            "env": environment,
            "category": category,
            "specs": listed_specs(category),
            "has_image": has_image,
            "tile_href": tile_href,
        },
    )


@router.get("/{net}/charts-plt")
async def get_plt_charts_home(net: str):
    """Absorbed into the gallery, which groups by the spec's own category."""
    return RedirectResponse(f"/{net}/charts#plt", status_code=308)


@router.get("/{net}/charts-agents")
async def get_agents_charts_home(net: str):
    """Absorbed into the gallery, which groups by the spec's own category."""
    return RedirectResponse(f"/{net}/charts#agents", status_code=308)
