# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x11\x63oncordium.health\"\x13\n\x11NodeHealthRequest\"\x14\n\x12NodeHealthResponse2^\n\x06Health\x12T\n\x05\x43heck\x12$.concordium.health.NodeHealthRequest\x1a%.concordium.health.NodeHealthResponseB3\n\x15\x63om.concordium.healthP\x01Z\x04./pb\xaa\x02\x11\x43oncordium.Healthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.concordium.healthP\001Z\004./pb\252\002\021Concordium.Health'
  _globals['_NODEHEALTHREQUEST']._serialized_start=35
  _globals['_NODEHEALTHREQUEST']._serialized_end=54
  _globals['_NODEHEALTHRESPONSE']._serialized_start=56
  _globals['_NODEHEALTHRESPONSE']._serialized_end=76
  _globals['_HEALTH']._serialized_start=78
  _globals['_HEALTH']._serialized_end=172
# @@protoc_insertion_point(module_scope)
